---
- name: Restart Adblock Proxy
  ansible.builtin.systemd:
    name: adblock-proxy
    state: restarted

- name: Restart Adblock Proxy Transparent
  ansible.builtin.systemd:
    name: adblock-proxy-transparent
    state: restarted

- name: Apply Transparent-Redirect iptables Rules
  ansible.builtin.command: iptables-restore /etc/iptables/rules.v4
  changed_when: true

- name: Reload Sysctl (Adblock Proxy)
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf
  changed_when: true
