# ~/.config/starship.toml

# The main format string now uses the $os variable instead of a hardcoded icon.
# The language/context modules are still included.
format = """\
[](bg:#030B16 fg:#7DF9AA)\
$os\
[](fg:#7DF9AA bg:#1C3A5E)\
$time\
[](fg:#1C3A5E bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[](bg:#4A4A4A fg:#FCF392)\
$python\
$nodejs\
$rust\
$golang\
$java\
$c\
$docker_context\
$conda\
[](fg:#4A4A4A bg:#030B16)\
$character\
"""

# --- Core Modules ---

[os]
disabled = false
style = "bg:#7DF9AA fg:#090c0c"
format = "[ $symbol ]($style)"

# The OS symbols table to define which icon to use for each OS.
[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[time]
disabled = false
time_format = "%R"
style = "bg:#1C3A5E fg:#8DFBD2"
format = '[ 󱑍 $time ]($style)'

[directory]
style = "fg:#E4E4E4 bg:#3B76F0"
# The folder icon has been removed as requested.
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = "󰝚 "
"Pictures"  = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:#1C3A5E bg:#FCF392"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "fg:#1C3A5E bg:#FCF392"
format = '[$all_status]($style)'
modified = "!"
untracked = "?"
stashed = ""
renamed = ""
deleted = ""

[git_metrics]
disabled = false
added_style = "fg:#1C3A5E bg:#FCF392"
format = '[ +$added]($added_style)'

# --- Language & Context Modules ---

[python]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[nodejs]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[c]
symbol = " "
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[cpp]
symbol = " "
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[rust]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[golang]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[php]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[java]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[kotlin]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[haskell]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[docker_context]
symbol = ""
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol $context ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[conda]
symbol = " "
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol $environment ](bg:#4A4A4A fg:#E4E4E4)]($style)'

[pixi]
style = "bg:#4A4A4A fg:#E4E4E4"
format = '[[ $symbol ($version) ](bg:#4A4A4A fg:#E4E4E4)]($style)'

# --- Final Prompt Character ---

[character]
success_symbol = '[➜](bold fg:#7DF9AA)'
error_symbol = '[✗](bold fg:#E84D44)'