- id: '1749006178316'
  alias: Midnight lights off
  description: ''
  triggers:
  - at: 00:00:00
    trigger: time
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.front_porch_sconces
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.stairs_main_lights
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.cat_room_main_lights
  mode: single
- id: '1749006624964'
  alias: Turn Off Lights - 30 mins Before Sunrise
  triggers:
  - event: sunrise
    offset: -00:30:00
    trigger: sun
  actions:
  - type: turn_off
    device_id: 0e45073a8cad750f8c80bf0153895436
    entity_id: ed5333fcb2eec2b5fa303e7d5bd8de7b
    domain: switch
  - type: turn_off
    device_id: 84b8c1d05331c8be32ba836d6504cbde
    entity_id: 8ceb46acdaa4116b6110386f81273a42
    domain: switch
  - type: turn_off
    device_id: 3cd76826d22d6cfff91a1b580f39029e
    entity_id: 53f03711b9db8e56d7381ca62149baee
    domain: switch
  - metadata: {}
    data: {}
    target:
      entity_id: scene.living_room_natural_light
    action: scene.turn_on
  mode: single
- id: '1749007348589'
  alias: Turn On Lights - 30 mins Before Sunset
  triggers:
  - event: sunset
    offset: -00:30:00
    trigger: sun
  actions:
  - type: turn_on
    device_id: 0e45073a8cad750f8c80bf0153895436
    entity_id: ed5333fcb2eec2b5fa303e7d5bd8de7b
    domain: switch
  - type: turn_on
    device_id: 84b8c1d05331c8be32ba836d6504cbde
    entity_id: 8ceb46acdaa4116b6110386f81273a42
    domain: switch
  - type: turn_on
    device_id: 3cd76826d22d6cfff91a1b580f39029e
    entity_id: 53f03711b9db8e56d7381ca62149baee
    domain: switch
  - metadata: {}
    data: {}
    target:
      entity_id: scene.living_room_natural_light
    action: scene.turn_on
  mode: single
- id: '1749147311203'
  alias: Hue Sync Box - Revert to Natural Light
  description: ''
  triggers:
  - type: not_running
    device_id: 573c1c67637fa9dc45de068eff843fb1
    entity_id: 010c91f4a6c5cf880088d0bc5347bab8
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 5
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: scene.living_room_natural_light
    action: scene.turn_on
  mode: single
- id: '1752083360234'
  alias: Pool Pump - On After Sunset
  description: Runs the pool pump for 6 hours after sunset if it's pool season and
    not too cold.
  triggers:
  - event: sunset
    trigger: sun
  conditions:
  - condition: state
    entity_id: input_boolean.pool_season
    state: 'on'
  - condition: numeric_state
    entity_id: weather.forecast_home
    attribute: temperature
    above: 40
  actions:
  - target:
      entity_id: switch.shelly1minig3_28372f21c5b8
    action: switch.turn_on
    data: {}
  - delay:
      hours: 6
      minutes: 0
      seconds: 0
      milliseconds: 0
  - target:
      entity_id: switch.shelly1minig3_28372f21c5b8
    action: switch.turn_off
    data: {}
  mode: single
- id: '1752083578214'
  alias: System - Auto Pool Season ON
  description: Turns on the Pool Season toggle on May 1st.
  triggers:
  - at: 00:01:00
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ now().month == 5 and now().day == 1 }}'
  actions:
  - target:
      entity_id: input_boolean.pool_season
    action: input_boolean.turn_on
  mode: single
- id: '1752083602361'
  alias: System - Auto Pool Season OFF
  description: Turns off the Pool Season toggle on October 1st.
  triggers:
  - at: 00:01:00
    trigger: time
  conditions:
  - condition: template
    value_template: '{{ now().month == 10 and now().day == 1 }}'
  actions:
  - target:
      entity_id: input_boolean.pool_season
    action: input_boolean.turn_off
  mode: single
- id: '1752084609900'
  alias: Vacuum - Upstairs Daily Cleaning
  description: Runs the upstairs vacuum once a day.
  triggers:
  - at: '11:00:00'
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: vacuum.cleanelizabeth1
    action: vacuum.start
  mode: single
- id: '1752084663411'
  alias: Vacuum - Downstairs High-Traffic Cleaning
  description: Runs the main floor vacuum 5 times daily, avoiding feeding times.
  triggers:
  - at: 08:30:00
    trigger: time
  - at: '12:00:00'
    trigger: time
  - at: '15:30:00'
    trigger: time
  - at: '19:00:00'
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: vacuum.cleanelizabeth2
    action: vacuum.start
    data: {}
  mode: single
- id: '1752200642222'
  alias: Garage Lights - Occupancy Control
  description: Turns light on with door open, turns off when occupancy is clear.
  triggers:
  - entity_id:
    - binary_sensor.garage_door_contact
    to: 'on'
    id: door_opened
    trigger: state
    from: 'off'
  - entity_id:
    - binary_sensor.garage_door_occupancy
    to: 'off'
    id: occupancy_cleared
    trigger: state
    from: 'on'
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: door_opened
      sequence:
      - action: switch.turn_on
        target:
          entity_id: switch.garage_main_lights
        data: {}
    - conditions:
      - condition: trigger
        id: occupancy_cleared
      - condition: state
        entity_id: binary_sensor.garage_door_contact
        state: 'off'
      sequence:
      - action: switch.turn_off
        target:
          entity_id: switch.garage_main_lights
        data: {}
  mode: single
- id: '1752541400967'
  alias: Smart Hot Water Recirculation Control
  description: Runs the recirculation pump on-demand with a global cooldown and separate
    logic for day and night.
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.guest_bathroom_occupancy
    - binary_sensor.half_bathroom_occupancy
    - binary_sensor.kitchen_occupancy_2
    - binary_sensor.main_bathroom_occupancy
    from: 'off'
    to: 'on'
  conditions:
  - condition: state
    entity_id: timer.water_heater_circulator_pump_cooldown
    state: idle
  actions:
  - target:
      entity_id: timer.water_heater_circulator_pump_cooldown
    action: timer.start
    data: {}
  - repeat:
      sequence:
      - choose:
        - conditions:
          - condition: sun
            after: sunset
          - condition: or
            conditions:
            - condition: state
              entity_id: switch.kitchen_main_lights
              state: 'on'
            - condition: state
              entity_id: switch.guest_bathroom_vanity_lights
              state: 'on'
            - condition: state
              state: 'on'
              entity_id: switch.half_bathroom_vanity_lights
          sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.shelly1minig3_28372f21c1dc
          - delay:
              hours: 0
              minutes: 5
              seconds: 0
              milliseconds: 0
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.shelly1minig3_28372f21c1dc
        - conditions:
          - condition: sun
            after: sunrise
          sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.shelly1minig3_28372f21c1dc
          - delay:
              hours: 0
              minutes: 5
              seconds: 0
              milliseconds: 0
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.shelly1minig3_28372f21c1dc
      - delay:
          hours: 0
          minutes: 25
          seconds: 0
          milliseconds: 0
      while:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.guest_bathroom_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.half_bathroom_occupancy
          state: 'on'
        - condition: state
          state: 'on'
          entity_id: binary_sensor.kitchen_occupancy_2
        - condition: state
          entity_id: binary_sensor.main_bathroom_occupancy
          state: 'on'
  mode: single
- id: '1757304692374'
  alias: Backyard floodlight
  description: Turn on floodlight on motion, off 15 minutes after last motion
  triggers:
  - entity_id: event.backyard_camera_motion_2
    to: 'on'
    trigger: state
  actions:
  - target:
      entity_id: switch.outdoor_floodlight_switch2
    action: switch.turn_on
  - wait_for_trigger:
    - entity_id: event.backyard_camera_motion_2
      to: 'off'
      trigger: state
  - delay: 00:15:00
  - target:
      entity_id: switch.outdoor_floodlight_switch2
    action: switch.turn_off
  mode: restart
