# Home Assistant Automations
# This file includes all automation files from the automations/ directory

# Include all automation files from the automations directory
automation: !include_dir_named automations/
