- platform: template
  sensors:
    living_room_fc56_vent_position:
      friendly_name: "Living Room (Left) Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.living_room_fc56_vent_2', 'current_tilt_position') | float(0) }}"

    living_room_5d8e_vent_position:
      friendly_name: "Living Room (Right) Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.living_room_5d8e_vent_2', 'current_tilt_position') | float(0) }}"

    main_bedroom_a96d_vent_position:
      friendly_name: "Main Bedroom (A) Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.main_bedroom_a96d_vent_2', 'current_tilt_position') | float(0) }}"

    main_bedroom_5c2b_vent_position:
      friendly_name: "Main Bedroom (B) Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.main_bedroom_5c2b_vent_2', 'current_tilt_position') | float(0) }}"

    main_bedroom_883f_vent_position:
      friendly_name: "Main Bedroom (C) Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.main_bedroom_883f_vent_2', 'current_tilt_position') | float(0) }}"

    kitchen_d124_vent_position:
      friendly_name: "Kitchen Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.kitchen_d124_vent_2', 'current_tilt_position') | float(0) }}"

    dining_room_7a28_vent_position:
      friendly_name: "Dining Room Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.dining_room_7a28_vent_2', 'current_tilt_position') | float(0) }}"

    hallway_907e_vent_position:
      friendly_name: "Hallway Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.hallway_907e_vent_2', 'current_tilt_position') | float(0) }}"

    guest_bedroom_2_1ec7_vent_position:
      friendly_name: "Guest Bedroom 2 Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.guest_bedroom_2_1ec7_vent_2', 'current_tilt_position') | float(0) }}"

    hallway_temperature:
      friendly_name: "Hallway Temperature"
      unit_of_measurement: "°F"
      device_class: temperature
      value_template: "{{ state_attr('climate.ecobee_thermostat', 'current_temperature') | float(0) }}"

    laundry_room_d189_vent_position:
      friendly_name: "Laundry Room Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.laundry_room_d189_vent_2', 'current_tilt_position') | float(0) }}"

    main_bathroom_f586_vent_position:
      friendly_name: "Main Bathroom Vent Position"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('cover.main_bathroom_f586_vent_2', 'current_tilt_position') | float(0) }}"

    salon_temperature:
      friendly_name: "Salon Temperature"
      unit_of_measurement: "°F"
      device_class: temperature
      value_template: "{{ states('sensor.basement_heatpump_basement_office_ac_ambient_temp') | float(0) }}"
