{
 "title": "Home Energy",
 "tags": [
  "energy",
  "homeassistant"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Current Grid Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.edgewater_road_power_minute_average\"}",
     "legendFormat": "Grid Power"
    }
   ]
  },
  {
   "title": "Energy Consumed Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh{entity=\"sensor.total_home_energy_energy_daily\"}",
     "legendFormat": "Energy Today"
    }
   ]
  },
  {
   "title": "Power Consumption History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.edgewater_road_power_minute_average\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "label_replace(homeassistant_sensor_power_w{entity=~\"sensor.edgewater_road_power_minute_average_.*\", friendly_name!=\"Heat Pump Water Heater\"}, \"custom_name\", \"$1\", \"friendly_name\", \"(.*) Power Minute Average.*\")",
     "legendFormat": "{{custom_name}}"
    }
   ]
  },
  {
   "title": "Circuit Breakdown",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(homeassistant_sensor_power_w{entity=~\"sensor.edgewater_road_power_minute_average_.*\", friendly_name!=\"Heat Pump Water Heater\"}, \"custom_name\", \"$1\", \"friendly_name\", \"(.*) Power Minute Average.*\")",
     "legendFormat": "{{custom_name}}"
    }
   ]
  }
 ]
}