{
 "title": "Home Climate",
 "tags": [
  "climate",
  "homeassistant"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Ground Floor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Living Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_fc56_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_5d8e_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.living_room_left_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.living_room_right_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_fc56_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.living_room_5d8e_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.living_room_left_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.living_room_right_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "title": "Kitchen",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.kitchen_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.kitchen_d124_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.kitchen_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.kitchen_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.kitchen_d124_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.kitchen_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Dining Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.dining_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.dining_room_7a28_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.dining_room_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.dining_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.dining_room_7a28_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.dining_room_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Hallway",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.hallway_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.hallway_907e_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.hallway_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.hallway_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.hallway_907e_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.hallway_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Main Bedroom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_a96d_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_5c2b_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_883f_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (C)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_a_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_b_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_c_vent_position\"}",
     "legendFormat": "Vent Position (C)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_a96d_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_5c2b_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bedroom_883f_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (C)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_a_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_b_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bedroom_c_vent_position\"}",
     "legendFormat": "Vent Position (C)"
    }
   ]
  },
  {
   "title": "Main Bathroom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bathroom_f586_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bathroom_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.main_bathroom_f586_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.main_bathroom_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Laundry Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.laundry_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.laundry_room_d189_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.laundry_room_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.laundry_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.laundry_room_d189_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.laundry_room_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Half Bathroom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.half_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.half_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    }
   ]
  },
  { "title": "Upstairs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Cat Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_3075_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.cat_room_3075_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_b58e_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.cat_room_b58e_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_3075_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.cat_room_3075_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.cat_room_b58e_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.cat_room_b58e_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "title": "Game Room",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_0c83_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_89ae_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_889a_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (C)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_a_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_b_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_889a_vent_position\"}",
     "legendFormat": "Vent Position (C)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_0c83_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_89ae_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.game_room_889a_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (C)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_a_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_b_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.game_room_889a_vent_position\"}",
     "legendFormat": "Vent Position (C)"
    }
   ]
  },
  {
   "title": "Guest Bedroom 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_8d6d_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_1_8d6d_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_8136_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_1_8136_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_8d6d_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_1_8d6d_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_1_8136_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (B)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_1_8136_vent_position\"}",
     "legendFormat": "Vent Position (B)"
    }
   ]
  },
  {
   "title": "Guest Bedroom 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_2_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_2_1ec7_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_2_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_2_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bedroom_2_1ec7_duct_temperature_2\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bedroom_2_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Guest Bathroom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bathroom_e5a3_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bathroom_e5a3_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bathroom_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.guest_bathroom_e5a3_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.guest_bathroom_e5a3_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  { "title": "Basement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Basement",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.7wq7_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.basement_4d79_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.basement_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.7wq7_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    },
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.basement_4d79_duct_temperature\"} * 1.8) + 32",
     "legendFormat": "Duct Temp (A)"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.basement_vent_position\"}",
     "legendFormat": "Vent Position (A)"
    }
   ]
  },
  {
   "title": "Salon",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.salon_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(homeassistant_sensor_temperature_celsius{entity=\"sensor.salon_temperature\"} * 1.8) + 32",
     "legendFormat": "Room Temp"
    }
   ]
  }
 ]
}