- alias: "Smart Hot Water Circulation"
  id: "smart_hot_water_circulation"
  mode: single
  max_exceeded: silent

  trigger:
    - platform: time_pattern
      minutes: "/5"

  condition:
    # 1. Cooldown Period (Must be > 30 mins since last stop)
    - condition: template
      value_template: >
        {% set stop_time = state_attr('input_datetime.smart_circulation_last_stopped', 'timestamp') | default(0) %}
        {{ (now().timestamp() - stop_time) > 1800 }}

    # 2. Check Temperatures (Start Condition)
    - condition: or
      conditions:
        # Kitchen (Copper) < 88F
        - condition: numeric_state
          entity_id: sensor.kitchen_water_temp_sensor
          below: 88
        # Bathrooms (Braided) < 85F
        - condition: numeric_state
          entity_id: sensor.main_bathroom_temp_sensor
          below: 85
        - condition: numeric_state
          entity_id: sensor.guest_bathroom_water_temp_sensor
          below: 85

  action:
    # Debug Notification
    - service: persistent_notification.create
      data:
        message: "Smart Water Circulation Triggered at {{ now() }}"
        title: "Automation Debug"

    # Start Pump
    - service: switch.turn_on
      target:
        entity_id: switch.shelly1minig3_28372f21c1dc

    # Monitor Loop (Wait for Cutoff)
    - wait_for_trigger:
        # Goal: Stop when ALL targets are met
        - platform: template
          value_template: >
            {{
              states('sensor.kitchen_water_temp_sensor')|float(0) > 92 and
              states('sensor.main_bathroom_temp_sensor')|float(0) > 92 and
              states('sensor.guest_bathroom_water_temp_sensor')|float(0) > 92
            }}

        # Safety: Stop if Bathrooms get too hot (Scald Protection)
        - platform: numeric_state
          entity_id: sensor.main_bathroom_temp_sensor
          above: 105
        - platform: numeric_state
          entity_id: sensor.guest_bathroom_water_temp_sensor
          above: 105

      timeout: "00:15:00"
      continue_on_timeout: true

    # Stop Pump
    - service: switch.turn_off
      target:
        entity_id: switch.shelly1minig3_28372f21c1dc

    # Update Last Stopped Time
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.smart_circulation_last_stopped
      data:
        timestamp: "{{ now().timestamp() }}"
