- alias: "Smart Hot Water Circulation"
  id: "smart_hot_water_circulation"
  mode: single
  max_exceeded: silent

  trigger:
    - platform: time_pattern
      minutes: "/5"

  condition:
    # 1. Cooldown Period (Must be > 30 mins since last stop)
    - condition: template
      value_template: >
        {% set stop_time = state_attr('input_datetime.smart_circulation_last_stopped', 'timestamp') | default(0) %}
        {{ (now().timestamp() - stop_time) > 600 }}

    # 2. Check Temperatures (Start Condition)
    - condition: or
      conditions:
        # Kitchen (Copper) < 88F
        - condition: numeric_state
          entity_id: sensor.kitchen_water_temp_sensor
          below: 85
        # Bathrooms (Calibrated) < 85F
        - condition: numeric_state
          entity_id: sensor.main_bathroom_temp_sensor
          below: 80
        - condition: numeric_state
          entity_id: sensor.guest_bathroom_water_temp_sensor
          below: 85

    # 3. Safety Check (Tank Capacity)
    - condition: numeric_state
      entity_id: sensor.econet_hpwh_hot_water
      above: 40
    - condition: numeric_state
      entity_id: climate.econet_hpwh
      attribute: current_temperature
      above: 100

  action:
    # Debug Notification
    # - service: persistent_notification.create
    #   data:
    #     message: "Smart Water Circulation Triggered at {{ now() }}"
    #     title: "Automation Debug"

    # Start Pump
    - service: switch.turn_on
      target:
        entity_id: switch.shelly1minig3_28372f21c1dc

    # Monitor Loop (Wait for Cutoff)
    - wait_for_trigger:
        # Goal: Stop when ALL targets are met
        - platform: template
          value_template: >
            {{
              states('sensor.kitchen_water_temp_sensor')|float(0) > 90 and
              states('sensor.main_bathroom_temp_sensor')|float(0) > 85 and
              states('sensor.guest_bathroom_water_temp_sensor')|float(0) > 90
            }}

        # Safety: Stop if Bathrooms get too hot (Scald Protection)
        - platform: numeric_state
          entity_id: sensor.main_bathroom_temp_sensor
          above: 105
        - platform: numeric_state
          entity_id: sensor.guest_bathroom_water_temp_sensor
          above: 105

        # Safety: Stop if Tank is low
        - platform: numeric_state
          entity_id: sensor.econet_hpwh_hot_water
          below: 40
        - platform: numeric_state
          entity_id: climate.econet_hpwh
          attribute: current_temperature
          below: 100

      timeout: "00:15:00"
      continue_on_timeout: true

    # Stop Pump
    - service: switch.turn_off
      target:
        entity_id: switch.shelly1minig3_28372f21c1dc

    # Update Last Stopped Time
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.smart_circulation_last_stopped
      data:
        timestamp: "{{ now().timestamp() }}"
