alias: Temperature Metrics Calculator
description: Calculates structured temperature drift, variance, and efficiency metrics for Grafana
trigger:
  - platform: time_pattern
    minutes: "/5"
    id: "periodic_calculation"
  - platform: state
    entity_id: 
      - climate.ecobee_thermostat
      - binary_sensor.kitchen_occupancy_2
      - binary_sensor.living_room_occupancy
      - binary_sensor.main_bedroom_occupancy
      - binary_sensor.guest_bedroom_2_occupancy
    id: "temperature_or_occupancy_changed"
condition: []
action:
  - service: system_log.write
    data:
      message: "Starting temperature metrics calculation"
      level: info
  
  # Calculate occupied vs unoccupied room temperatures
  - service: system_log.write
    data:
      message: |
        TEMPERATURE_METRICS: {
          "timestamp": "{{ now().isoformat() }}",
          "ecobee_setpoint": {{ state_attr("climate.ecobee_thermostat", "temperature") }},
          "ecobee_mode": "{{ states("climate.ecobee_thermostat") }}",
          "occupied_rooms": {
            "kitchen": {
              "temperature": {{ state_attr("climate.kitchen_room_3", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.kitchen_occupancy_2") }}",
              "vent_position": {{ state_attr("cover.kitchen_d124_vent", "current_tilt_position") }},
              "drift_from_setpoint": {{ state_attr("climate.kitchen_room_3", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            },
            "living_room": {
              "temperature": {{ state_attr("climate.living_room_room_3", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.living_room_occupancy") }}",
              "vent_position": {{ (state_attr("cover.living_room_fc56_vent", "current_tilt_position") | float + state_attr("cover.living_room_5d8e_vent", "current_tilt_position") | float) / 2 }},
              "drift_from_setpoint": {{ state_attr("climate.living_room_room_3", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            },
            "main_bedroom": {
              "temperature": {{ state_attr("climate.main_bedroom_room_2", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.main_bedroom_occupancy") }}",
              "vent_position": {{ (state_attr("cover.main_bedroom_883f_vent", "current_tilt_position") | float + state_attr("cover.main_bedroom_a96d_vent", "current_tilt_position") | float) / 2 }},
              "drift_from_setpoint": {{ state_attr("climate.main_bedroom_room_2", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            },
            "guest_bedroom_2": {
              "temperature": {{ state_attr("climate.guest_bedroom_2_room_2", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.guest_bedroom_2_occupancy") }}",
              "vent_position": {{ state_attr("cover.guest_bedroom_2_1ec7_vent", "current_tilt_position") }},
              "drift_from_setpoint": {{ state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            }
          },
          "unoccupied_rooms": {
            "main_bathroom": {
              "temperature": {{ state_attr("climate.main_bathroom_room_2", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.main_bathroom_occupancy") }}",
              "vent_position": {{ state_attr("cover.main_bathroom_f586_vent", "current_tilt_position") }},
              "drift_from_setpoint": {{ state_attr("climate.main_bathroom_room_2", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            },
            "laundry_room": {
              "temperature": {{ state_attr("climate.laundry_room_room", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.laundry_room_occupancy") }}",
              "vent_position": {{ state_attr("cover.laundry_room_d189_vent", "current_tilt_position") }},
              "drift_from_setpoint": {{ state_attr("climate.laundry_room_room", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            },
            "dining_room": {
              "temperature": {{ state_attr("climate.dining_room_room", "current_temperature") }},
              "occupancy": "{{ states("binary_sensor.dining_room_occupancy") }}",
              "vent_position": {{ state_attr("cover.dining_room_7a28_vent", "current_tilt_position") }},
              "drift_from_setpoint": {{ state_attr("climate.dining_room_room", "current_temperature") | float - state_attr("climate.ecobee_thermostat", "temperature") | float }}
            }
          }
        }
      level: info

  # Calculate variance metrics
  - service: system_log.write
    data:
      message: |
        TEMPERATURE_VARIANCE_METRICS: {
          "timestamp": "{{ now().isoformat() }}",
          "occupied_room_temperatures": [
            {{ state_attr("climate.kitchen_room_3", "current_temperature") | float if states("binary_sensor.kitchen_occupancy_2") == "on" else "null" }},
            {{ state_attr("climate.living_room_room_3", "current_temperature") | float if states("binary_sensor.living_room_occupancy") == "on" else "null" }},
            {{ state_attr("climate.main_bedroom_room_2", "current_temperature") | float if states("binary_sensor.main_bedroom_occupancy") == "on" else "null" }},
            {{ state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float if states("binary_sensor.guest_bedroom_2_occupancy") == "on" else "null" }}
          ],
          "unoccupied_room_temperatures": [
            {{ state_attr("climate.main_bathroom_room_2", "current_temperature") | float if states("binary_sensor.main_bathroom_occupancy") == "off" else "null" }},
            {{ state_attr("climate.laundry_room_room", "current_temperature") | float if states("binary_sensor.laundry_room_occupancy") == "off" else "null" }},
            {{ state_attr("climate.dining_room_room", "current_temperature") | float if states("binary_sensor.dining_room_occupancy") == "off" else "null" }}
          ],
          "occupied_rooms_count": {{ [states("binary_sensor.kitchen_occupancy_2") == "on", states("binary_sensor.living_room_occupancy") == "on", states("binary_sensor.main_bedroom_occupancy") == "on", states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list | length }},
          "unoccupied_rooms_count": {{ [states("binary_sensor.kitchen_occupancy_2") == "off", states("binary_sensor.living_room_occupancy") == "off", states("binary_sensor.main_bedroom_occupancy") == "off", states("binary_sensor.guest_bedroom_2_occupancy") == "off", states("binary_sensor.main_bathroom_occupancy") == "off", states("binary_sensor.laundry_room_occupancy") == "off", states("binary_sensor.dining_room_occupancy") == "off"] | select | list | length }}
        }
      level: info

  # Calculate efficiency scores
  - service: system_log.write
    data:
      message: |
        EFFICIENCY_METRICS: {
          "timestamp": "{{ now().isoformat() }}",
          "temperature_efficiency": {
            "occupied_rooms_variance": "{{ ([state_attr("climate.kitchen_room_3", "current_temperature") | float if states("binary_sensor.kitchen_occupancy_2") == "on", state_attr("climate.living_room_room_3", "current_temperature") | float if states("binary_sensor.living_room_occupancy") == "on", state_attr("climate.main_bedroom_room_2", "current_temperature") | float if states("binary_sensor.main_bedroom_occupancy") == "on", state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float if states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list) | map("float") | max - ([state_attr("climate.kitchen_room_3", "current_temperature") | float if states("binary_sensor.kitchen_occupancy_2") == "on", state_attr("climate.living_room_room_3", "current_temperature") | float if states("binary_sensor.living_room_occupancy") == "on", state_attr("climate.main_bedroom_room_2", "current_temperature") | float if states("binary_sensor.main_bedroom_occupancy") == "on", state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float if states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list) | map("float") | min }}",
            "unoccupied_rooms_variance": "{{ ([state_attr("climate.main_bathroom_room_2", "current_temperature") | float if states("binary_sensor.main_bathroom_occupancy") == "off", state_attr("climate.laundry_room_room", "current_temperature") | float if states("binary_sensor.laundry_room_occupancy") == "off", state_attr("climate.dining_room_room", "current_temperature") | float if states("binary_sensor.dining_room_occupancy") == "off"] | select | list) | map("float") | max - ([state_attr("climate.main_bathroom_room_2", "current_temperature") | float if states("binary_sensor.main_bathroom_occupancy") == "off", state_attr("climate.laundry_room_room", "current_temperature") | float if states("binary_sensor.laundry_room_occupancy") == "off", state_attr("climate.dining_room_room", "current_temperature") | float if states("binary_sensor.dining_room_occupancy") == "off"] | select | list) | map("float") | min }}",
            "overall_efficiency_score": "{{ 100 - (([state_attr("climate.kitchen_room_3", "current_temperature") | float if states("binary_sensor.kitchen_occupancy_2") == "on", state_attr("climate.living_room_room_3", "current_temperature") | float if states("binary_sensor.living_room_occupancy") == "on", state_attr("climate.main_bedroom_room_2", "current_temperature") | float if states("binary_sensor.main_bedroom_occupancy") == "on", state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float if states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list) | map("float") | max - ([state_attr("climate.kitchen_room_3", "current_temperature") | float if states("binary_sensor.kitchen_occupancy_2") == "on", state_attr("climate.living_room_room_3", "current_temperature") | float if states("binary_sensor.living_room_occupancy") == "on", state_attr("climate.main_bedroom_room_2", "current_temperature") | float if states("binary_sensor.main_bedroom_occupancy") == "on", state_attr("climate.guest_bedroom_2_room_2", "current_temperature") | float if states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list) | map("float") | min) * 10) }}"
          },
          "occupancy_efficiency": {
            "occupied_rooms_count": {{ [states("binary_sensor.kitchen_occupancy_2") == "on", states("binary_sensor.living_room_occupancy") == "on", states("binary_sensor.main_bedroom_occupancy") == "on", states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list | length }},
            "total_rooms_monitored": 7,
            "occupancy_percentage": "{{ ([states("binary_sensor.kitchen_occupancy_2") == "on", states("binary_sensor.living_room_occupancy") == "on", states("binary_sensor.main_bedroom_occupancy") == "on", states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list | length) / 7 * 100 }}",
            "vent_control_efficiency": "{{ 100 if ([states("binary_sensor.kitchen_occupancy_2") == "on", states("binary_sensor.living_room_occupancy") == "on", states("binary_sensor.main_bedroom_occupancy") == "on", states("binary_sensor.guest_bedroom_2_occupancy") == "on"] | select | list | length) > 0 else 0 }}"
          }
        }
      level: info

  - service: system_log.write
    data:
      message: "Temperature metrics calculation completed"
      level: info

mode: restart
