# playbook_test_connection.yml
---
- name: Test connection to Windows VMs via VMware Tools
  hosts: vmware_tag_tanium_client_314
  gather_facts: no
  tasks:
    - name: Verify connection with basic command
      win_shell: "(Get-WmiObject -Class Win32_OperatingSystem).Caption"
      register: os_check
      changed_when: false  # Treat this task as unchanged if it succeeds

    - name: Display OS type
      debug:
        var: os_check.stdout
