---
- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    state: restarted
    daemon_reload: true

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
