---
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Gallery
  ansible.builtin.systemd:
    name: media-gallery-gallery.service
    state: restarted
    daemon_reload: true

- name: Restart Thumb
  ansible.builtin.systemd:
    name: media-gallery-thumb.service
    state: restarted
    daemon_reload: true

- name: Restart Trash
  ansible.builtin.systemd:
    name: media-gallery-trash.service
    state: restarted
    daemon_reload: true

- name: Restart Upload
  ansible.builtin.systemd:
    name: media-gallery-upload.service
    state: restarted
    daemon_reload: true

- name: Save tg iptables
  ansible.builtin.shell: "mkdir -p /etc/iptables && iptables-save > /etc/iptables/rules.v4"
  changed_when: true

- name: Reload SSH
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
  failed_when: false
